version: "3.2"
services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    entrypoint: ["sh", "./docker/php/entrypoint.sh"]
    privileged: true
    environment:
      # Fake credentials for Localstack
      AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
      AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      TEST_ENV: ${TEST_ENV}
      LOCALHOST: ${LOCALHOST}
      PHP_IDE_CONFIG: "serverName=docker"
    depends_on:
#      - "localstack"
      - "redis"
      - "mysql"
    ports:
      - '8001:9000'
      - '8002:9001'
    networks:
      - service-php-v1
    volumes:
      - ./:/app
  nginx:
    build: ./docker/nginx
    privileged: true
    working_dir: /app
    ports:
      - '8000:80'
      - '8443:443'
    networks:
      - service-php-v1
    volumes:
      - ./:/app
      - ./vendor:/app/vendor
      - ./target:/app/target
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certificate.crt:/etc/nginx/conf.d/certificate.crt
      - ./docker/nginx/certificate.key:/etc/nginx/conf.d/certificate.key
      - ./docker/nginx/logs:/var/log/nginx
    links:
      - php
    depends_on:
      - php
  cepapi-mock:
    build:
      context: .
      dockerfile: ./docker/node/cepapi-mock/Dockerfile
    privileged: false
    ports:
      - "3000:3000"
    volumes:
      - ./docker/node/cepapi-mock/server:/app/server
      - ./docker/node/cepapi-mock/public:/app/public
    networks:
      - service-php-v1
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - service-php-v1
  mysql:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: store
      MYSQL_ROOT_PASSWORD: store
    networks:
      - service-php-v1
  localstack:
    image: localstack/localstack
    privileged: true
    ports:
      - "4566:4566"
      - "4567-4582:4567-4582"
      - "9070:9070"
      - "8080:8080"
    environment:
      SERVICES: sqs,lambda,cloudwatch,s3
      DOCKER_HOST: unix:///var/run/docker.sock
      PORT_WEB_UI: 9070
      # metodo antigo
      #      LAMBDA_EXECUTOR: local
      # Compatibilidade com todas as linguagens
      # https://docs.localstack.cloud/references/configuration/#lambda
      #      LAMBDA_EXECUTOR: docker-reuse
      LAMBDA_EXECUTOR: docker
      LAMBDA_REMOTE_DOCKER: 1
      LAMBDA_DOCKER_NETWORK: service-php-v1
      DEBUG: 1
      HOSTNAME_EXTERNAL: localstack
      LEGACY_DIRECTORIES: 1
    networks:
      - service-php-v1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/localstack:/tmp/localstack
networks:
  service-php-v1:
    external: true
